version: 1
data_directory: data/
log_directory: log/
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(filename)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

#    info_file_handler:
#        class: logging.handlers.RotatingFileHandler
#        level: INFO
#        formatter: simple
#        filename: ${log_directory}/info.log
#        maxBytes: 10485760 # 10MB
#        backupCount: 20
#        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: ${log_directory}/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console,error_file_handler]
#    handlers: [console, info_file_handler,error_file_handler]